#%RAML 0.8
title: Mod Users BL
version: v1
baseUri: http://github.com/org/folio/mod-users-bl

documentation:
    - title: Business Logic Users API
      content: A front end for mod-users, authn/credentials and auth/permissions

resourceTypes:
  - collection: !include ../raml-util/rtypes/collection.raml
  - collection-item: !include ../raml-util/rtypes/item-collection.raml
  - get-only: !include ../raml-util/rtypes/get-only.raml
  - post-empty-body: !include ../raml-util/rtypes/post-empty-body.raml
  
#schemas:
#    - compositeUser: !include schemas/compositeUser.json

/users:
    /{username}:
        type:
          get-only:
    /by-id:
        /{userid}:
            get-only:

